[servers]
hardanger

[servers:vars]
host_vm_files_dir="repCXL-ansible"
# VM creation config, parameterized to ID (must change for multiple VM)
image_url=https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
image_path="{{ host_vm_files_dir }}/ubuntu2404-server.img"
# defult VM config
vm_id=0
vm_disk_path="{{ host_vm_files_dir }}/vm{{ vm_id }}.qcow2"
cxl_numa_node=0
memory_nodes=3
# force VM re-creation
force=false

[vms]
hardanger repcxl_id=0

[vms:vars]
ansible_user=
ansible_connection=ssh
ansible_ssh_private_key_file=~/.ssh/ansible_key
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
# paths (remote are relative to wherever SSH lands on) 
local_repo="{{ inventory_dir }}/../../"
local_result_folder="{{ local_repo }}/bench-outputs/"
remote_dir="repCXL-bench"
repcxl_coordinator_id=0
ycsb_remote_source_dir="YCSB"

ycsb_workload="workloada_64_large"

# either a file in config/ or "config/ansible.toml" which is generated 
# with the parameters below
repcxl_config="config/ansible.toml"
# repCXL config parameters (passed to template)
round_time=1_000
algorithm="async_best_effort"
; process_list=[0, 1, 2, 3]
process_list=[0]
pipeline=true
read_retries=0
; read_offset=0.89

[all:vars]
ansible_python_interpreter=/usr/bin/python3