# RepCXL configuration file
# Example usage: <binary> -c config/example.toml

# Memory nodes. In the VM setup, memory regions of the CXL node from the host 
# are exposed as PCI devices with inter-vm shared memory 
mem_nodes = [
"/sys/bus/pci/devices/0000:00:03.0/resource2", 
"/sys/bus/pci/devices/0000:00:04.0/resource2",
"/sys/bus/pci/devices/0000:00:05.0/resource2"
] 

# Total size of each memory node in bytes, padded to chunk size
mem_size = 1_000_000_000 
chunk_size = 64

# (required) unique identifier for the repCXL instance. Can be passed with -i
id = 0 

# List of process IDs in the cluster. Can be specified as:
#   - A number (4) → generates IDs [0, 1, 2, 3]
#   - A range string ("0..3" or "0-3") → generates IDs [0, 1, 2, 3]
#   - An array ([0, 1, 2, 3]) → explicit list of IDs
processes = [0, 1, 2, 3]

# (ns) Time to wait for all processes to start up (in nanoseconds)
startup_delay = 1000000000

# (ns) Duration of the synchronous round (in nanoseconds)
round_time = 1000 

# Replication algorithm: "monster", "sync_best_effort", "async_best_effort"
algorithm = "fmonster"

# Number of times to retry a read operation if it returns a dirty read
read_retries = 0

# CPU core to pin the repCXL write thread to (optional, default is None)
core_affinity = 2 

