---
- name: Deploy repCXL from GitHub
  hosts: vms
  tasks:
    - set_fact:
        repcxl_id: "{{ inventory_hostname | regex_replace('^p','') | int }}"
        
    - name: clean up the remote directory
      file:
        path: "{{ remote_dir }}"
        state: absent

    - name: kill repcxl processes
      shell: |
        pkill -f ycsb_client || true
        pkill -f repcxl || true
      args:
        executable: /bin/bash
      become: true