- name: Run YCSB cliient benchmark
  hosts: vms
  serial: 4
  gather_facts: no
  tasks:

    - set_fact:
        repcxl_id: "{{ inventory_hostname | regex_replace('^p','') | int }}"

    - name: create remote work directory if it doesn't exist
      file:
        path: "{{ remote_dir }}"
        state: directory
        mode: '0755'

    - name: synchronize YCSB
      synchronize:
        src: "{{ local_repo }}/ycsb"
        dest: "{{ remote_dir }}/"
    
    - name: get absolute path of remote work directory
      shell: realpath {{ remote_dir }}
      register: remote_abs

    - name: get ycsb files path (workloads, traces)
      set_fact:
        yfp: "{{ remote_abs.stdout }}/ycsb"
    
    - name: generate workload file for YCSB client
      shell: |
        bin/ycsb load basic -P {{ yfp }}/workloads/{{ ycsb_workload }} > {{ yfp }}/traces/{{ ycsb_workload }}_load.dat
        bin/ycsb run basic -P {{ yfp }}/workloads/{{ ycsb_workload }} > {{ yfp }}/traces/{{ ycsb_workload }}_run.dat
      args:
        executable: /bin/bash
        chdir: "{{ ycsb_remote_source_dir }}"

